#!/usr/bin/bash

set -e

echo "Syncing NVIDIA Flatpak runtimes"
flatpak update --appstream

echo "Detecting NVIDIA driver version"
NVIDIA_VERSION=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader)

echo "Installing NVIDIA Flatpak runtimes version ${NVIDIA_VERSION}"
flatpak install -y flathub org.freedesktop.Platform.GL.nvidia-${NVIDIA_VERSION//./-} org.freedesktop.Platform.GL32.nvidia-${NVIDIA_VERSION//./-}
echo "NVIDIA Flatpak runtimes installation complete"
