#!/usr/bin/bash

set -e

echo "Starting Flatpak system update..."

if /usr/bin/flatpak update -y --noninteractive --system; then
    echo "Flatpak system update completed successfully."
else
    echo "Flatpak system update failed."
    exit 1
fi
